version: '1.0'

services:
  nginx:
    image: nginx
    container_name: "laravel-nginx"
    ports:
      - "80:80"
    volumes:
      - ./src:/src
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build: ./php
    container_name: "laravel-php"
    volumes:
      - ./src:/src
  sqlsrv:
    container_name: "laravel-sqlsrv"
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: <your password>
  redis:
    image: redis:alpine
    container_name: "laravel-redis"
    ports: 
      - 6379:6379
